<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PcCountiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('pc_counties')->delete();

        \DB::table('pc_counties')->insert(array(
            0 => array(
                'id' => 1,
                'cod_district' => '01',
                'cod_county' => '06',
                'desig_county' => 'Castelo de Paiva',
            ),
            1 => array(
                'id' => 2,
                'cod_district' => '01',
                'cod_county' => '07',
                'desig_county' => 'Espinho',
            ),
            2 => array(
                'id' => 3,
                'cod_district' => '01',
                'cod_county' => '08',
                'desig_county' => 'Estarreja',
            ),
            3 => array(
                'id' => 4,
                'cod_district' => '01',
                'cod_county' => '09',
                'desig_county' => 'Santa Maria da Feira',
            ),
            4 => array(
                'id' => 5,
                'cod_district' => '01',
                'cod_county' => '10',
                'desig_county' => 'Ílhavo',
            ),
            5 => array(
                'id' => 6,
                'cod_district' => '01',
                'cod_county' => '11',
                'desig_county' => 'Mealhada',
            ),
            6 => array(
                'id' => 7,
                'cod_district' => '01',
                'cod_county' => '12',
                'desig_county' => 'Murtosa',
            ),
            7 => array(
                'id' => 8,
                'cod_district' => '01',
                'cod_county' => '13',
                'desig_county' => 'Oliveira de Azeméis',
            ),
            8 => array(
                'id' => 9,
                'cod_district' => '01',
                'cod_county' => '14',
                'desig_county' => 'Oliveira do Bairro',
            ),
            9 => array(
                'id' => 10,
                'cod_district' => '01',
                'cod_county' => '15',
                'desig_county' => 'Ovar',
            ),
            10 => array(
                'id' => 11,
                'cod_district' => '01',
                'cod_county' => '16',
                'desig_county' => 'São João da Madeira',
            ),
            11 => array(
                'id' => 12,
                'cod_district' => '01',
                'cod_county' => '17',
                'desig_county' => 'Sever do Vouga',
            ),
            12 => array(
                'id' => 13,
                'cod_district' => '01',
                'cod_county' => '18',
                'desig_county' => 'Vagos',
            ),
            13 => array(
                'id' => 14,
                'cod_district' => '01',
                'cod_county' => '19',
                'desig_county' => 'Vale de Cambra',
            ),
            14 => array(
                'id' => 15,
                'cod_district' => '01',
                'cod_county' => '01',
                'desig_county' => 'Águeda',
            ),
            15 => array(
                'id' => 16,
                'cod_district' => '01',
                'cod_county' => '02',
                'desig_county' => 'Albergaria-a-Velha',
            ),
            16 => array(
                'id' => 17,
                'cod_district' => '01',
                'cod_county' => '03',
                'desig_county' => 'Anadia',
            ),
            17 => array(
                'id' => 18,
                'cod_district' => '01',
                'cod_county' => '04',
                'desig_county' => 'Arouca',
            ),
            18 => array(
                'id' => 19,
                'cod_district' => '01',
                'cod_county' => '05',
                'desig_county' => 'Aveiro',
            ),
            19 => array(
                'id' => 20,
                'cod_district' => '02',
                'cod_county' => '06',
                'desig_county' => 'Castro Verde',
            ),
            20 => array(
                'id' => 21,
                'cod_district' => '02',
                'cod_county' => '07',
                'desig_county' => 'Cuba',
            ),
            21 => array(
                'id' => 22,
                'cod_district' => '02',
                'cod_county' => '08',
                'desig_county' => 'Ferreira do Alentejo',
            ),
            22 => array(
                'id' => 23,
                'cod_district' => '02',
                'cod_county' => '09',
                'desig_county' => 'Mértola',
            ),
            23 => array(
                'id' => 24,
                'cod_district' => '02',
                'cod_county' => '10',
                'desig_county' => 'Moura',
            ),
            24 => array(
                'id' => 25,
                'cod_district' => '02',
                'cod_county' => '11',
                'desig_county' => 'Odemira',
            ),
            25 => array(
                'id' => 26,
                'cod_district' => '02',
                'cod_county' => '12',
                'desig_county' => 'Ourique',
            ),
            26 => array(
                'id' => 27,
                'cod_district' => '02',
                'cod_county' => '13',
                'desig_county' => 'Serpa',
            ),
            27 => array(
                'id' => 28,
                'cod_district' => '02',
                'cod_county' => '14',
                'desig_county' => 'Vidigueira',
            ),
            28 => array(
                'id' => 29,
                'cod_district' => '02',
                'cod_county' => '01',
                'desig_county' => 'Aljustrel',
            ),
            29 => array(
                'id' => 30,
                'cod_district' => '02',
                'cod_county' => '02',
                'desig_county' => 'Almodôvar',
            ),
            30 => array(
                'id' => 31,
                'cod_district' => '02',
                'cod_county' => '03',
                'desig_county' => 'Alvito',
            ),
            31 => array(
                'id' => 32,
                'cod_district' => '02',
                'cod_county' => '04',
                'desig_county' => 'Barrancos',
            ),
            32 => array(
                'id' => 33,
                'cod_district' => '02',
                'cod_county' => '05',
                'desig_county' => 'Beja',
            ),
            33 => array(
                'id' => 34,
                'cod_district' => '03',
                'cod_county' => '06',
                'desig_county' => 'Esposende',
            ),
            34 => array(
                'id' => 35,
                'cod_district' => '03',
                'cod_county' => '07',
                'desig_county' => 'Fafe',
            ),
            35 => array(
                'id' => 36,
                'cod_district' => '03',
                'cod_county' => '08',
                'desig_county' => 'Guimarães',
            ),
            36 => array(
                'id' => 37,
                'cod_district' => '03',
                'cod_county' => '09',
                'desig_county' => 'Póvoa de Lanhoso',
            ),
            37 => array(
                'id' => 38,
                'cod_district' => '03',
                'cod_county' => '10',
                'desig_county' => 'Terras de Bouro',
            ),
            38 => array(
                'id' => 39,
                'cod_district' => '03',
                'cod_county' => '11',
                'desig_county' => 'Vieira do Minho',
            ),
            39 => array(
                'id' => 40,
                'cod_district' => '03',
                'cod_county' => '12',
                'desig_county' => 'Vila Nova de Famalicão',
            ),
            40 => array(
                'id' => 41,
                'cod_district' => '03',
                'cod_county' => '13',
                'desig_county' => 'Vila Verde',
            ),
            41 => array(
                'id' => 42,
                'cod_district' => '03',
                'cod_county' => '14',
                'desig_county' => 'Vizela',
            ),
            42 => array(
                'id' => 43,
                'cod_district' => '03',
                'cod_county' => '01',
                'desig_county' => 'Amares',
            ),
            43 => array(
                'id' => 44,
                'cod_district' => '03',
                'cod_county' => '02',
                'desig_county' => 'Barcelos',
            ),
            44 => array(
                'id' => 45,
                'cod_district' => '03',
                'cod_county' => '03',
                'desig_county' => 'Braga',
            ),
            45 => array(
                'id' => 46,
                'cod_district' => '03',
                'cod_county' => '04',
                'desig_county' => 'Cabeceiras de Basto',
            ),
            46 => array(
                'id' => 47,
                'cod_district' => '03',
                'cod_county' => '05',
                'desig_county' => 'Celorico de Basto',
            ),
            47 => array(
                'id' => 48,
                'cod_district' => '04',
                'cod_county' => '06',
                'desig_county' => 'Miranda do Douro',
            ),
            48 => array(
                'id' => 49,
                'cod_district' => '04',
                'cod_county' => '07',
                'desig_county' => 'Mirandela',
            ),
            49 => array(
                'id' => 50,
                'cod_district' => '04',
                'cod_county' => '08',
                'desig_county' => 'Mogadouro',
            ),
            50 => array(
                'id' => 51,
                'cod_district' => '04',
                'cod_county' => '09',
                'desig_county' => 'Torre de Moncorvo',
            ),
            51 => array(
                'id' => 52,
                'cod_district' => '04',
                'cod_county' => '10',
                'desig_county' => 'Vila Flor',
            ),
            52 => array(
                'id' => 53,
                'cod_district' => '04',
                'cod_county' => '11',
                'desig_county' => 'Vimioso',
            ),
            53 => array(
                'id' => 54,
                'cod_district' => '04',
                'cod_county' => '12',
                'desig_county' => 'Vinhais',
            ),
            54 => array(
                'id' => 55,
                'cod_district' => '04',
                'cod_county' => '01',
                'desig_county' => 'Alfândega da Fé',
            ),
            55 => array(
                'id' => 56,
                'cod_district' => '04',
                'cod_county' => '02',
                'desig_county' => 'Bragança',
            ),
            56 => array(
                'id' => 57,
                'cod_district' => '04',
                'cod_county' => '03',
                'desig_county' => 'Carrazeda de Ansiães',
            ),
            57 => array(
                'id' => 58,
                'cod_district' => '04',
                'cod_county' => '04',
                'desig_county' => 'Freixo de Espada à Cinta',
            ),
            58 => array(
                'id' => 59,
                'cod_district' => '04',
                'cod_county' => '05',
                'desig_county' => 'Macedo de Cavaleiros',
            ),
            59 => array(
                'id' => 60,
                'cod_district' => '05',
                'cod_county' => '06',
                'desig_county' => 'Oleiros',
            ),
            60 => array(
                'id' => 61,
                'cod_district' => '05',
                'cod_county' => '07',
                'desig_county' => 'Penamacor',
            ),
            61 => array(
                'id' => 62,
                'cod_district' => '05',
                'cod_county' => '08',
                'desig_county' => 'Proença-a-Nova',
            ),
            62 => array(
                'id' => 63,
                'cod_district' => '05',
                'cod_county' => '09',
                'desig_county' => 'Sertã',
            ),
            63 => array(
                'id' => 64,
                'cod_district' => '05',
                'cod_county' => '10',
                'desig_county' => 'Vila de Rei',
            ),
            64 => array(
                'id' => 65,
                'cod_district' => '05',
                'cod_county' => '11',
                'desig_county' => 'Vila Velha de Ródão',
            ),
            65 => array(
                'id' => 66,
                'cod_district' => '05',
                'cod_county' => '01',
                'desig_county' => 'Belmonte',
            ),
            66 => array(
                'id' => 67,
                'cod_district' => '05',
                'cod_county' => '02',
                'desig_county' => 'Castelo Branco',
            ),
            67 => array(
                'id' => 68,
                'cod_district' => '05',
                'cod_county' => '03',
                'desig_county' => 'Covilhã',
            ),
            68 => array(
                'id' => 69,
                'cod_district' => '05',
                'cod_county' => '04',
                'desig_county' => 'Fundão',
            ),
            69 => array(
                'id' => 70,
                'cod_district' => '05',
                'cod_county' => '05',
                'desig_county' => 'Idanha-a-Nova',
            ),
            70 => array(
                'id' => 71,
                'cod_district' => '06',
                'cod_county' => '06',
                'desig_county' => 'Góis',
            ),
            71 => array(
                'id' => 72,
                'cod_district' => '06',
                'cod_county' => '07',
                'desig_county' => 'Lousã',
            ),
            72 => array(
                'id' => 73,
                'cod_district' => '06',
                'cod_county' => '08',
                'desig_county' => 'Mira',
            ),
            73 => array(
                'id' => 74,
                'cod_district' => '06',
                'cod_county' => '09',
                'desig_county' => 'Miranda do Corvo',
            ),
            74 => array(
                'id' => 75,
                'cod_district' => '06',
                'cod_county' => '10',
                'desig_county' => 'Montemor-o-Velho',
            ),
            75 => array(
                'id' => 76,
                'cod_district' => '06',
                'cod_county' => '11',
                'desig_county' => 'Oliveira do Hospital',
            ),
            76 => array(
                'id' => 77,
                'cod_district' => '06',
                'cod_county' => '12',
                'desig_county' => 'Pampilhosa da Serra',
            ),
            77 => array(
                'id' => 78,
                'cod_district' => '06',
                'cod_county' => '13',
                'desig_county' => 'Penacova',
            ),
            78 => array(
                'id' => 79,
                'cod_district' => '06',
                'cod_county' => '14',
                'desig_county' => 'Penela',
            ),
            79 => array(
                'id' => 80,
                'cod_district' => '06',
                'cod_county' => '15',
                'desig_county' => 'Soure',
            ),
            80 => array(
                'id' => 81,
                'cod_district' => '06',
                'cod_county' => '16',
                'desig_county' => 'Tábua',
            ),
            81 => array(
                'id' => 82,
                'cod_district' => '06',
                'cod_county' => '17',
                'desig_county' => 'Vila Nova de Poiares',
            ),
            82 => array(
                'id' => 83,
                'cod_district' => '06',
                'cod_county' => '01',
                'desig_county' => 'Arganil',
            ),
            83 => array(
                'id' => 84,
                'cod_district' => '06',
                'cod_county' => '02',
                'desig_county' => 'Cantanhede',
            ),
            84 => array(
                'id' => 85,
                'cod_district' => '06',
                'cod_county' => '03',
                'desig_county' => 'Coimbra',
            ),
            85 => array(
                'id' => 86,
                'cod_district' => '06',
                'cod_county' => '04',
                'desig_county' => 'Condeixa-a-Nova',
            ),
            86 => array(
                'id' => 87,
                'cod_district' => '06',
                'cod_county' => '05',
                'desig_county' => 'Figueira da Foz',
            ),
            87 => array(
                'id' => 88,
                'cod_district' => '07',
                'cod_county' => '06',
                'desig_county' => 'Montemor-o-Novo',
            ),
            88 => array(
                'id' => 89,
                'cod_district' => '07',
                'cod_county' => '07',
                'desig_county' => 'Mora',
            ),
            89 => array(
                'id' => 90,
                'cod_district' => '07',
                'cod_county' => '08',
                'desig_county' => 'Mourão',
            ),
            90 => array(
                'id' => 91,
                'cod_district' => '07',
                'cod_county' => '09',
                'desig_county' => 'Portel',
            ),
            91 => array(
                'id' => 92,
                'cod_district' => '07',
                'cod_county' => '10',
                'desig_county' => 'Redondo',
            ),
            92 => array(
                'id' => 93,
                'cod_district' => '07',
                'cod_county' => '11',
                'desig_county' => 'Reguengos de Monsaraz',
            ),
            93 => array(
                'id' => 94,
                'cod_district' => '07',
                'cod_county' => '12',
                'desig_county' => 'Vendas Novas',
            ),
            94 => array(
                'id' => 95,
                'cod_district' => '07',
                'cod_county' => '13',
                'desig_county' => 'Viana do Alentejo',
            ),
            95 => array(
                'id' => 96,
                'cod_district' => '07',
                'cod_county' => '14',
                'desig_county' => 'Vila Viçosa',
            ),
            96 => array(
                'id' => 97,
                'cod_district' => '07',
                'cod_county' => '01',
                'desig_county' => 'Alandroal',
            ),
            97 => array(
                'id' => 98,
                'cod_district' => '07',
                'cod_county' => '02',
                'desig_county' => 'Arraiolos',
            ),
            98 => array(
                'id' => 99,
                'cod_district' => '07',
                'cod_county' => '03',
                'desig_county' => 'Borba',
            ),
            99 => array(
                'id' => 100,
                'cod_district' => '07',
                'cod_county' => '04',
                'desig_county' => 'Estremoz',
            ),
            100 => array(
                'id' => 101,
                'cod_district' => '07',
                'cod_county' => '05',
                'desig_county' => 'Évora',
            ),
            101 => array(
                'id' => 102,
                'cod_district' => '08',
                'cod_county' => '06',
                'desig_county' => 'Lagoa (Algarve)',
            ),
            102 => array(
                'id' => 103,
                'cod_district' => '08',
                'cod_county' => '07',
                'desig_county' => 'Lagos',
            ),
            103 => array(
                'id' => 104,
                'cod_district' => '08',
                'cod_county' => '08',
                'desig_county' => 'Loulé',
            ),
            104 => array(
                'id' => 105,
                'cod_district' => '08',
                'cod_county' => '09',
                'desig_county' => 'Monchique',
            ),
            105 => array(
                'id' => 106,
                'cod_district' => '08',
                'cod_county' => '10',
                'desig_county' => 'Olhão',
            ),
            106 => array(
                'id' => 107,
                'cod_district' => '08',
                'cod_county' => '11',
                'desig_county' => 'Portimão',
            ),
            107 => array(
                'id' => 108,
                'cod_district' => '08',
                'cod_county' => '12',
                'desig_county' => 'São Brás de Alportel',
            ),
            108 => array(
                'id' => 109,
                'cod_district' => '08',
                'cod_county' => '13',
                'desig_county' => 'Silves',
            ),
            109 => array(
                'id' => 110,
                'cod_district' => '08',
                'cod_county' => '14',
                'desig_county' => 'Tavira',
            ),
            110 => array(
                'id' => 111,
                'cod_district' => '08',
                'cod_county' => '15',
                'desig_county' => 'Vila do Bispo',
            ),
            111 => array(
                'id' => 112,
                'cod_district' => '08',
                'cod_county' => '16',
                'desig_county' => 'Vila Real de Santo António',
            ),
            112 => array(
                'id' => 113,
                'cod_district' => '08',
                'cod_county' => '01',
                'desig_county' => 'Albufeira',
            ),
            113 => array(
                'id' => 114,
                'cod_district' => '08',
                'cod_county' => '02',
                'desig_county' => 'Alcoutim',
            ),
            114 => array(
                'id' => 115,
                'cod_district' => '08',
                'cod_county' => '03',
                'desig_county' => 'Aljezur',
            ),
            115 => array(
                'id' => 116,
                'cod_district' => '08',
                'cod_county' => '04',
                'desig_county' => 'Castro Marim',
            ),
            116 => array(
                'id' => 117,
                'cod_district' => '08',
                'cod_county' => '05',
                'desig_county' => 'Faro',
            ),
            117 => array(
                'id' => 118,
                'cod_district' => '09',
                'cod_county' => '06',
                'desig_county' => 'Gouveia',
            ),
            118 => array(
                'id' => 119,
                'cod_district' => '09',
                'cod_county' => '07',
                'desig_county' => 'Guarda',
            ),
            119 => array(
                'id' => 120,
                'cod_district' => '09',
                'cod_county' => '08',
                'desig_county' => 'Manteigas',
            ),
            120 => array(
                'id' => 121,
                'cod_district' => '09',
                'cod_county' => '09',
                'desig_county' => 'Meda',
            ),
            121 => array(
                'id' => 122,
                'cod_district' => '09',
                'cod_county' => '10',
                'desig_county' => 'Pinhel',
            ),
            122 => array(
                'id' => 123,
                'cod_district' => '09',
                'cod_county' => '11',
                'desig_county' => 'Sabugal',
            ),
            123 => array(
                'id' => 124,
                'cod_district' => '09',
                'cod_county' => '12',
                'desig_county' => 'Seia',
            ),
            124 => array(
                'id' => 125,
                'cod_district' => '09',
                'cod_county' => '13',
                'desig_county' => 'Trancoso',
            ),
            125 => array(
                'id' => 126,
                'cod_district' => '09',
                'cod_county' => '14',
                'desig_county' => 'Vila Nova de Foz Côa',
            ),
            126 => array(
                'id' => 127,
                'cod_district' => '09',
                'cod_county' => '01',
                'desig_county' => 'Aguiar da Beira',
            ),
            127 => array(
                'id' => 128,
                'cod_district' => '09',
                'cod_county' => '02',
                'desig_county' => 'Almeida',
            ),
            128 => array(
                'id' => 129,
                'cod_district' => '09',
                'cod_county' => '03',
                'desig_county' => 'Celorico da Beira',
            ),
            129 => array(
                'id' => 130,
                'cod_district' => '09',
                'cod_county' => '04',
                'desig_county' => 'Figueira de Castelo Rodrigo',
            ),
            130 => array(
                'id' => 131,
                'cod_district' => '09',
                'cod_county' => '05',
                'desig_county' => 'Fornos de Algodres',
            ),
            131 => array(
                'id' => 132,
                'cod_district' => '10',
                'cod_county' => '06',
                'desig_county' => 'Caldas da Rainha',
            ),
            132 => array(
                'id' => 133,
                'cod_district' => '10',
                'cod_county' => '07',
                'desig_county' => 'Castanheira de Pêra',
            ),
            133 => array(
                'id' => 134,
                'cod_district' => '10',
                'cod_county' => '08',
                'desig_county' => 'Figueiró dos Vinhos',
            ),
            134 => array(
                'id' => 135,
                'cod_district' => '10',
                'cod_county' => '09',
                'desig_county' => 'Leiria',
            ),
            135 => array(
                'id' => 136,
                'cod_district' => '10',
                'cod_county' => '10',
                'desig_county' => 'Marinha Grande',
            ),
            136 => array(
                'id' => 137,
                'cod_district' => '10',
                'cod_county' => '11',
                'desig_county' => 'Nazaré',
            ),
            137 => array(
                'id' => 138,
                'cod_district' => '10',
                'cod_county' => '12',
                'desig_county' => 'Óbidos',
            ),
            138 => array(
                'id' => 139,
                'cod_district' => '10',
                'cod_county' => '13',
                'desig_county' => 'Pedrógão Grande',
            ),
            139 => array(
                'id' => 140,
                'cod_district' => '10',
                'cod_county' => '14',
                'desig_county' => 'Peniche',
            ),
            140 => array(
                'id' => 141,
                'cod_district' => '10',
                'cod_county' => '15',
                'desig_county' => 'Pombal',
            ),
            141 => array(
                'id' => 142,
                'cod_district' => '10',
                'cod_county' => '16',
                'desig_county' => 'Porto de Mós',
            ),
            142 => array(
                'id' => 143,
                'cod_district' => '10',
                'cod_county' => '01',
                'desig_county' => 'Alcobaça',
            ),
            143 => array(
                'id' => 144,
                'cod_district' => '10',
                'cod_county' => '02',
                'desig_county' => 'Alvaiázere',
            ),
            144 => array(
                'id' => 145,
                'cod_district' => '10',
                'cod_county' => '03',
                'desig_county' => 'Ansião',
            ),
            145 => array(
                'id' => 146,
                'cod_district' => '10',
                'cod_county' => '04',
                'desig_county' => 'Batalha',
            ),
            146 => array(
                'id' => 147,
                'cod_district' => '10',
                'cod_county' => '05',
                'desig_county' => 'Bombarral',
            ),
            147 => array(
                'id' => 148,
                'cod_district' => '11',
                'cod_county' => '06',
                'desig_county' => 'Lisboa',
            ),
            148 => array(
                'id' => 149,
                'cod_district' => '11',
                'cod_county' => '07',
                'desig_county' => 'Loures',
            ),
            149 => array(
                'id' => 150,
                'cod_district' => '11',
                'cod_county' => '08',
                'desig_county' => 'Lourinhã',
            ),
            150 => array(
                'id' => 151,
                'cod_district' => '11',
                'cod_county' => '09',
                'desig_county' => 'Mafra',
            ),
            151 => array(
                'id' => 152,
                'cod_district' => '11',
                'cod_county' => '10',
                'desig_county' => 'Oeiras',
            ),
            152 => array(
                'id' => 153,
                'cod_district' => '11',
                'cod_county' => '11',
                'desig_county' => 'Sintra',
            ),
            153 => array(
                'id' => 154,
                'cod_district' => '11',
                'cod_county' => '12',
                'desig_county' => 'Sobral de Monte Agraço',
            ),
            154 => array(
                'id' => 155,
                'cod_district' => '11',
                'cod_county' => '13',
                'desig_county' => 'Torres Vedras',
            ),
            155 => array(
                'id' => 156,
                'cod_district' => '11',
                'cod_county' => '14',
                'desig_county' => 'Vila Franca de Xira',
            ),
            156 => array(
                'id' => 157,
                'cod_district' => '11',
                'cod_county' => '15',
                'desig_county' => 'Amadora',
            ),
            157 => array(
                'id' => 158,
                'cod_district' => '11',
                'cod_county' => '16',
                'desig_county' => 'Odivelas',
            ),
            158 => array(
                'id' => 159,
                'cod_district' => '11',
                'cod_county' => '01',
                'desig_county' => 'Alenquer',
            ),
            159 => array(
                'id' => 160,
                'cod_district' => '11',
                'cod_county' => '02',
                'desig_county' => 'Arruda dos Vinhos',
            ),
            160 => array(
                'id' => 161,
                'cod_district' => '11',
                'cod_county' => '03',
                'desig_county' => 'Azambuja',
            ),
            161 => array(
                'id' => 162,
                'cod_district' => '11',
                'cod_county' => '04',
                'desig_county' => 'Cadaval',
            ),
            162 => array(
                'id' => 163,
                'cod_district' => '11',
                'cod_county' => '05',
                'desig_county' => 'Cascais',
            ),
            163 => array(
                'id' => 164,
                'cod_district' => '12',
                'cod_county' => '06',
                'desig_county' => 'Crato',
            ),
            164 => array(
                'id' => 165,
                'cod_district' => '12',
                'cod_county' => '07',
                'desig_county' => 'Elvas',
            ),
            165 => array(
                'id' => 166,
                'cod_district' => '12',
                'cod_county' => '08',
                'desig_county' => 'Fronteira',
            ),
            166 => array(
                'id' => 167,
                'cod_district' => '12',
                'cod_county' => '09',
                'desig_county' => 'Gavião',
            ),
            167 => array(
                'id' => 168,
                'cod_district' => '12',
                'cod_county' => '10',
                'desig_county' => 'Marvão',
            ),
            168 => array(
                'id' => 169,
                'cod_district' => '12',
                'cod_county' => '11',
                'desig_county' => 'Monforte',
            ),
            169 => array(
                'id' => 170,
                'cod_district' => '12',
                'cod_county' => '12',
                'desig_county' => 'Nisa',
            ),
            170 => array(
                'id' => 171,
                'cod_district' => '12',
                'cod_county' => '13',
                'desig_county' => 'Ponte de Sor',
            ),
            171 => array(
                'id' => 172,
                'cod_district' => '12',
                'cod_county' => '14',
                'desig_county' => 'Portalegre',
            ),
            172 => array(
                'id' => 173,
                'cod_district' => '12',
                'cod_county' => '15',
                'desig_county' => 'Sousel',
            ),
            173 => array(
                'id' => 174,
                'cod_district' => '12',
                'cod_county' => '01',
                'desig_county' => 'Alter do Chão',
            ),
            174 => array(
                'id' => 175,
                'cod_district' => '12',
                'cod_county' => '02',
                'desig_county' => 'Arronches',
            ),
            175 => array(
                'id' => 176,
                'cod_district' => '12',
                'cod_county' => '03',
                'desig_county' => 'Avis',
            ),
            176 => array(
                'id' => 177,
                'cod_district' => '12',
                'cod_county' => '04',
                'desig_county' => 'Campo Maior',
            ),
            177 => array(
                'id' => 178,
                'cod_district' => '12',
                'cod_county' => '05',
                'desig_county' => 'Castelo de Vide',
            ),
            178 => array(
                'id' => 179,
                'cod_district' => '13',
                'cod_county' => '06',
                'desig_county' => 'Maia',
            ),
            179 => array(
                'id' => 180,
                'cod_district' => '13',
                'cod_county' => '07',
                'desig_county' => 'Marco de Canaveses',
            ),
            180 => array(
                'id' => 181,
                'cod_district' => '13',
                'cod_county' => '08',
                'desig_county' => 'Matosinhos',
            ),
            181 => array(
                'id' => 182,
                'cod_district' => '13',
                'cod_county' => '09',
                'desig_county' => 'Paços de Ferreira',
            ),
            182 => array(
                'id' => 183,
                'cod_district' => '13',
                'cod_county' => '10',
                'desig_county' => 'Paredes',
            ),
            183 => array(
                'id' => 184,
                'cod_district' => '13',
                'cod_county' => '11',
                'desig_county' => 'Penafiel',
            ),
            184 => array(
                'id' => 185,
                'cod_district' => '13',
                'cod_county' => '12',
                'desig_county' => 'Porto',
            ),
            185 => array(
                'id' => 186,
                'cod_district' => '13',
                'cod_county' => '13',
                'desig_county' => 'Póvoa de Varzim',
            ),
            186 => array(
                'id' => 187,
                'cod_district' => '13',
                'cod_county' => '14',
                'desig_county' => 'Santo Tirso',
            ),
            187 => array(
                'id' => 188,
                'cod_district' => '13',
                'cod_county' => '15',
                'desig_county' => 'Valongo',
            ),
            188 => array(
                'id' => 189,
                'cod_district' => '13',
                'cod_county' => '16',
                'desig_county' => 'Vila do Conde',
            ),
            189 => array(
                'id' => 190,
                'cod_district' => '13',
                'cod_county' => '17',
                'desig_county' => 'Vila Nova de Gaia',
            ),
            190 => array(
                'id' => 191,
                'cod_district' => '13',
                'cod_county' => '18',
                'desig_county' => 'Trofa',
            ),
            191 => array(
                'id' => 192,
                'cod_district' => '13',
                'cod_county' => '01',
                'desig_county' => 'Amarante',
            ),
            192 => array(
                'id' => 193,
                'cod_district' => '13',
                'cod_county' => '02',
                'desig_county' => 'Baião',
            ),
            193 => array(
                'id' => 194,
                'cod_district' => '13',
                'cod_county' => '03',
                'desig_county' => 'Felgueiras',
            ),
            194 => array(
                'id' => 195,
                'cod_district' => '13',
                'cod_county' => '04',
                'desig_county' => 'Gondomar',
            ),
            195 => array(
                'id' => 196,
                'cod_district' => '13',
                'cod_county' => '05',
                'desig_county' => 'Lousada',
            ),
            196 => array(
                'id' => 197,
                'cod_district' => '14',
                'cod_county' => '06',
                'desig_county' => 'Cartaxo',
            ),
            197 => array(
                'id' => 198,
                'cod_district' => '14',
                'cod_county' => '07',
                'desig_county' => 'Chamusca',
            ),
            198 => array(
                'id' => 199,
                'cod_district' => '14',
                'cod_county' => '08',
                'desig_county' => 'Constância',
            ),
            199 => array(
                'id' => 200,
                'cod_district' => '14',
                'cod_county' => '09',
                'desig_county' => 'Coruche',
            ),
            200 => array(
                'id' => 201,
                'cod_district' => '14',
                'cod_county' => '10',
                'desig_county' => 'Entroncamento',
            ),
            201 => array(
                'id' => 202,
                'cod_district' => '14',
                'cod_county' => '11',
                'desig_county' => 'Ferreira do Zêzere',
            ),
            202 => array(
                'id' => 203,
                'cod_district' => '14',
                'cod_county' => '12',
                'desig_county' => 'Golegã',
            ),
            203 => array(
                'id' => 204,
                'cod_district' => '14',
                'cod_county' => '13',
                'desig_county' => 'Mação',
            ),
            204 => array(
                'id' => 205,
                'cod_district' => '14',
                'cod_county' => '14',
                'desig_county' => 'Rio Maior',
            ),
            205 => array(
                'id' => 206,
                'cod_district' => '14',
                'cod_county' => '15',
                'desig_county' => 'Salvaterra de Magos',
            ),
            206 => array(
                'id' => 207,
                'cod_district' => '14',
                'cod_county' => '16',
                'desig_county' => 'Santarém',
            ),
            207 => array(
                'id' => 208,
                'cod_district' => '14',
                'cod_county' => '17',
                'desig_county' => 'Sardoal',
            ),
            208 => array(
                'id' => 209,
                'cod_district' => '14',
                'cod_county' => '18',
                'desig_county' => 'Tomar',
            ),
            209 => array(
                'id' => 210,
                'cod_district' => '14',
                'cod_county' => '19',
                'desig_county' => 'Torres Novas',
            ),
            210 => array(
                'id' => 211,
                'cod_district' => '14',
                'cod_county' => '20',
                'desig_county' => 'Vila Nova da Barquinha',
            ),
            211 => array(
                'id' => 212,
                'cod_district' => '14',
                'cod_county' => '21',
                'desig_county' => 'Ourém',
            ),
            212 => array(
                'id' => 213,
                'cod_district' => '14',
                'cod_county' => '01',
                'desig_county' => 'Abrantes',
            ),
            213 => array(
                'id' => 214,
                'cod_district' => '14',
                'cod_county' => '02',
                'desig_county' => 'Alcanena',
            ),
            214 => array(
                'id' => 215,
                'cod_district' => '14',
                'cod_county' => '03',
                'desig_county' => 'Almeirim',
            ),
            215 => array(
                'id' => 216,
                'cod_district' => '14',
                'cod_county' => '04',
                'desig_county' => 'Alpiarça',
            ),
            216 => array(
                'id' => 217,
                'cod_district' => '14',
                'cod_county' => '05',
                'desig_county' => 'Benavente',
            ),
            217 => array(
                'id' => 218,
                'cod_district' => '15',
                'cod_county' => '06',
                'desig_county' => 'Moita',
            ),
            218 => array(
                'id' => 219,
                'cod_district' => '15',
                'cod_county' => '07',
                'desig_county' => 'Montijo',
            ),
            219 => array(
                'id' => 220,
                'cod_district' => '15',
                'cod_county' => '08',
                'desig_county' => 'Palmela',
            ),
            220 => array(
                'id' => 221,
                'cod_district' => '15',
                'cod_county' => '09',
                'desig_county' => 'Santiago do Cacém',
            ),
            221 => array(
                'id' => 222,
                'cod_district' => '15',
                'cod_county' => '10',
                'desig_county' => 'Seixal',
            ),
            222 => array(
                'id' => 223,
                'cod_district' => '15',
                'cod_county' => '11',
                'desig_county' => 'Sesimbra',
            ),
            223 => array(
                'id' => 224,
                'cod_district' => '15',
                'cod_county' => '12',
                'desig_county' => 'Setúbal',
            ),
            224 => array(
                'id' => 225,
                'cod_district' => '15',
                'cod_county' => '13',
                'desig_county' => 'Sines',
            ),
            225 => array(
                'id' => 226,
                'cod_district' => '15',
                'cod_county' => '01',
                'desig_county' => 'Alcácer do Sal',
            ),
            226 => array(
                'id' => 227,
                'cod_district' => '15',
                'cod_county' => '02',
                'desig_county' => 'Alcochete',
            ),
            227 => array(
                'id' => 228,
                'cod_district' => '15',
                'cod_county' => '03',
                'desig_county' => 'Almada',
            ),
            228 => array(
                'id' => 229,
                'cod_district' => '15',
                'cod_county' => '04',
                'desig_county' => 'Barreiro',
            ),
            229 => array(
                'id' => 230,
                'cod_district' => '15',
                'cod_county' => '05',
                'desig_county' => 'Grândola',
            ),
            230 => array(
                'id' => 231,
                'cod_district' => '16',
                'cod_county' => '06',
                'desig_county' => 'Ponte da Barca',
            ),
            231 => array(
                'id' => 232,
                'cod_district' => '16',
                'cod_county' => '07',
                'desig_county' => 'Ponte de Lima',
            ),
            232 => array(
                'id' => 233,
                'cod_district' => '16',
                'cod_county' => '08',
                'desig_county' => 'Valença',
            ),
            233 => array(
                'id' => 234,
                'cod_district' => '16',
                'cod_county' => '09',
                'desig_county' => 'Viana do Castelo',
            ),
            234 => array(
                'id' => 235,
                'cod_district' => '16',
                'cod_county' => '10',
                'desig_county' => 'Vila Nova de Cerveira',
            ),
            235 => array(
                'id' => 236,
                'cod_district' => '16',
                'cod_county' => '01',
                'desig_county' => 'Arcos de Valdevez',
            ),
            236 => array(
                'id' => 237,
                'cod_district' => '16',
                'cod_county' => '02',
                'desig_county' => 'Caminha',
            ),
            237 => array(
                'id' => 238,
                'cod_district' => '16',
                'cod_county' => '03',
                'desig_county' => 'Melgaço',
            ),
            238 => array(
                'id' => 239,
                'cod_district' => '16',
                'cod_county' => '04',
                'desig_county' => 'Monção',
            ),
            239 => array(
                'id' => 240,
                'cod_district' => '16',
                'cod_county' => '05',
                'desig_county' => 'Paredes de Coura',
            ),
            240 => array(
                'id' => 241,
                'cod_district' => '17',
                'cod_county' => '05',
                'desig_county' => 'Mondim de Basto',
            ),
            241 => array(
                'id' => 242,
                'cod_district' => '17',
                'cod_county' => '06',
                'desig_county' => 'Montalegre',
            ),
            242 => array(
                'id' => 243,
                'cod_district' => '17',
                'cod_county' => '07',
                'desig_county' => 'Murça',
            ),
            243 => array(
                'id' => 244,
                'cod_district' => '17',
                'cod_county' => '08',
                'desig_county' => 'Peso da Régua',
            ),
            244 => array(
                'id' => 245,
                'cod_district' => '17',
                'cod_county' => '09',
                'desig_county' => 'Ribeira de Pena',
            ),
            245 => array(
                'id' => 246,
                'cod_district' => '17',
                'cod_county' => '10',
                'desig_county' => 'Sabrosa',
            ),
            246 => array(
                'id' => 247,
                'cod_district' => '17',
                'cod_county' => '11',
                'desig_county' => 'Santa Marta de Penaguião',
            ),
            247 => array(
                'id' => 248,
                'cod_district' => '17',
                'cod_county' => '12',
                'desig_county' => 'Valpaços',
            ),
            248 => array(
                'id' => 249,
                'cod_district' => '17',
                'cod_county' => '13',
                'desig_county' => 'Vila Pouca de Aguiar',
            ),
            249 => array(
                'id' => 250,
                'cod_district' => '17',
                'cod_county' => '14',
                'desig_county' => 'Vila Real',
            ),
            250 => array(
                'id' => 251,
                'cod_district' => '17',
                'cod_county' => '01',
                'desig_county' => 'Alijó',
            ),
            251 => array(
                'id' => 252,
                'cod_district' => '17',
                'cod_county' => '02',
                'desig_county' => 'Boticas',
            ),
            252 => array(
                'id' => 253,
                'cod_district' => '17',
                'cod_county' => '03',
                'desig_county' => 'Chaves',
            ),
            253 => array(
                'id' => 254,
                'cod_district' => '17',
                'cod_county' => '04',
                'desig_county' => 'Mesão Frio',
            ),
            254 => array(
                'id' => 255,
                'cod_district' => '18',
                'cod_county' => '05',
                'desig_county' => 'Lamego',
            ),
            255 => array(
                'id' => 256,
                'cod_district' => '18',
                'cod_county' => '06',
                'desig_county' => 'Mangualde',
            ),
            256 => array(
                'id' => 257,
                'cod_district' => '18',
                'cod_county' => '07',
                'desig_county' => 'Moimenta da Beira',
            ),
            257 => array(
                'id' => 258,
                'cod_district' => '18',
                'cod_county' => '08',
                'desig_county' => 'Mortágua',
            ),
            258 => array(
                'id' => 259,
                'cod_district' => '18',
                'cod_county' => '09',
                'desig_county' => 'Nelas',
            ),
            259 => array(
                'id' => 260,
                'cod_district' => '18',
                'cod_county' => '10',
                'desig_county' => 'Oliveira de Frades',
            ),
            260 => array(
                'id' => 261,
                'cod_district' => '18',
                'cod_county' => '11',
                'desig_county' => 'Penalva do Castelo',
            ),
            261 => array(
                'id' => 262,
                'cod_district' => '18',
                'cod_county' => '12',
                'desig_county' => 'Penedono',
            ),
            262 => array(
                'id' => 263,
                'cod_district' => '18',
                'cod_county' => '13',
                'desig_county' => 'Resende',
            ),
            263 => array(
                'id' => 264,
                'cod_district' => '18',
                'cod_county' => '14',
                'desig_county' => 'Santa Comba Dão',
            ),
            264 => array(
                'id' => 265,
                'cod_district' => '18',
                'cod_county' => '15',
                'desig_county' => 'São João da Pesqueira',
            ),
            265 => array(
                'id' => 266,
                'cod_district' => '18',
                'cod_county' => '16',
                'desig_county' => 'São Pedro do Sul',
            ),
            266 => array(
                'id' => 267,
                'cod_district' => '18',
                'cod_county' => '17',
                'desig_county' => 'Sátão',
            ),
            267 => array(
                'id' => 268,
                'cod_district' => '18',
                'cod_county' => '18',
                'desig_county' => 'Sernancelhe',
            ),
            268 => array(
                'id' => 269,
                'cod_district' => '18',
                'cod_county' => '19',
                'desig_county' => 'Tabuaço',
            ),
            269 => array(
                'id' => 270,
                'cod_district' => '18',
                'cod_county' => '20',
                'desig_county' => 'Tarouca',
            ),
            270 => array(
                'id' => 271,
                'cod_district' => '18',
                'cod_county' => '21',
                'desig_county' => 'Tondela',
            ),
            271 => array(
                'id' => 272,
                'cod_district' => '18',
                'cod_county' => '22',
                'desig_county' => 'Vila Nova de Paiva',
            ),
            272 => array(
                'id' => 273,
                'cod_district' => '18',
                'cod_county' => '23',
                'desig_county' => 'Viseu',
            ),
            273 => array(
                'id' => 274,
                'cod_district' => '18',
                'cod_county' => '24',
                'desig_county' => 'Vouzela',
            ),
            274 => array(
                'id' => 275,
                'cod_district' => '18',
                'cod_county' => '01',
                'desig_county' => 'Armamar',
            ),
            275 => array(
                'id' => 276,
                'cod_district' => '18',
                'cod_county' => '02',
                'desig_county' => 'Carregal do Sal',
            ),
            276 => array(
                'id' => 277,
                'cod_district' => '18',
                'cod_county' => '03',
                'desig_county' => 'Castro Daire',
            ),
            277 => array(
                'id' => 278,
                'cod_district' => '18',
                'cod_county' => '04',
                'desig_county' => 'Cinfães',
            ),
            278 => array(
                'id' => 279,
                'cod_district' => '31',
                'cod_county' => '05',
                'desig_county' => 'Ponta do Sol',
            ),
            279 => array(
                'id' => 280,
                'cod_district' => '31',
                'cod_county' => '06',
                'desig_county' => 'Porto Moniz',
            ),
            280 => array(
                'id' => 281,
                'cod_district' => '31',
                'cod_county' => '07',
                'desig_county' => 'Ribeira Brava',
            ),
            281 => array(
                'id' => 282,
                'cod_district' => '31',
                'cod_county' => '08',
                'desig_county' => 'Santa Cruz',
            ),
            282 => array(
                'id' => 283,
                'cod_district' => '31',
                'cod_county' => '09',
                'desig_county' => 'Santana',
            ),
            283 => array(
                'id' => 284,
                'cod_district' => '31',
                'cod_county' => '10',
                'desig_county' => 'São Vicente',
            ),
            284 => array(
                'id' => 285,
                'cod_district' => '31',
                'cod_county' => '01',
                'desig_county' => 'Calheta (Madeira)',
            ),
            285 => array(
                'id' => 286,
                'cod_district' => '31',
                'cod_county' => '02',
                'desig_county' => 'Câmara de Lobos',
            ),
            286 => array(
                'id' => 287,
                'cod_district' => '31',
                'cod_county' => '03',
                'desig_county' => 'Funchal',
            ),
            287 => array(
                'id' => 288,
                'cod_district' => '31',
                'cod_county' => '04',
                'desig_county' => 'Machico',
            ),
            288 => array(
                'id' => 289,
                'cod_district' => '32',
                'cod_county' => '01',
                'desig_county' => 'Porto Santo',
            ),
            289 => array(
                'id' => 290,
                'cod_district' => '41',
                'cod_county' => '01',
                'desig_county' => 'Vila do Porto',
            ),
            290 => array(
                'id' => 291,
                'cod_district' => '42',
                'cod_county' => '05',
                'desig_county' => 'Ribeira Grande',
            ),
            291 => array(
                'id' => 292,
                'cod_district' => '42',
                'cod_county' => '06',
                'desig_county' => 'Vila Franca do Campo',
            ),
            292 => array(
                'id' => 293,
                'cod_district' => '42',
                'cod_county' => '01',
                'desig_county' => 'Lagoa (São Miguel)',
            ),
            293 => array(
                'id' => 294,
                'cod_district' => '42',
                'cod_county' => '02',
                'desig_county' => 'Nordeste',
            ),
            294 => array(
                'id' => 295,
                'cod_district' => '42',
                'cod_county' => '03',
                'desig_county' => 'Ponta Delgada',
            ),
            295 => array(
                'id' => 296,
                'cod_district' => '42',
                'cod_county' => '04',
                'desig_county' => 'Povoação',
            ),
            296 => array(
                'id' => 297,
                'cod_district' => '43',
                'cod_county' => '01',
                'desig_county' => 'Angra do Heroísmo',
            ),
            297 => array(
                'id' => 298,
                'cod_district' => '43',
                'cod_county' => '02',
                'desig_county' => 'Praia da Vitória',
            ),
            298 => array(
                'id' => 299,
                'cod_district' => '44',
                'cod_county' => '01',
                'desig_county' => 'Santa Cruz da Graciosa',
            ),
            299 => array(
                'id' => 300,
                'cod_district' => '45',
                'cod_county' => '01',
                'desig_county' => 'Calheta (São Jorge)',
            ),
            300 => array(
                'id' => 301,
                'cod_district' => '45',
                'cod_county' => '02',
                'desig_county' => 'Velas',
            ),
            301 => array(
                'id' => 302,
                'cod_district' => '46',
                'cod_county' => '01',
                'desig_county' => 'Lajes do Pico',
            ),
            302 => array(
                'id' => 303,
                'cod_district' => '46',
                'cod_county' => '02',
                'desig_county' => 'Madalena',
            ),
            303 => array(
                'id' => 304,
                'cod_district' => '46',
                'cod_county' => '03',
                'desig_county' => 'São Roque do Pico',
            ),
            304 => array(
                'id' => 305,
                'cod_district' => '47',
                'cod_county' => '01',
                'desig_county' => 'Horta',
            ),
            305 => array(
                'id' => 306,
                'cod_district' => '48',
                'cod_county' => '01',
                'desig_county' => 'Lajes das Flores',
            ),
            306 => array(
                'id' => 307,
                'cod_district' => '48',
                'cod_county' => '02',
                'desig_county' => 'Santa Cruz das Flores',
            ),
            307 => array(
                'id' => 308,
                'cod_district' => '49',
                'cod_county' => '01',
                'desig_county' => 'Corvo',
            ),
        ));

    }
}
